WITH REST_REVIEW_MAX_CNT AS (
    SELECT MEMBER_ID, COUNT(*) AS CNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY CNT DESC
    LIMIT 1
)

SELECT A.MEMBER_NAME, B.REVIEW_TEXT, DATE_FORMAT(B.REVIEW_DATE, "%Y-%m-%d") REVIEW_DATE
FROM MEMBER_PROFILE A
LEFT JOIN (
    SELECT *
    FROM REST_REVIEW
    WHERE MEMBER_ID = (SELECT MEMBER_ID FROM REST_REVIEW_MAX_CNT)
) B ON A.MEMBER_ID = B.MEMBER_ID
WHERE B.MEMBER_ID IS NOT NULL
ORDER BY REVIEW_DATE, REVIEW_TEXT;