SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT B.USER_ID) AS PUCHASED_USERS,
    ROUND(COUNT(DISTINCT B.USER_ID) / (SELECT COUNT(*)
                                       FROM USER_INFO 
                                       WHERE JOINED LIKE "2021%"), 1) AS PUCHASED_RATIO
FROM USER_INFO A
INNER JOIN ONLINE_SALE B ON A.USER_ID = B.USER_ID
WHERE A.JOINED LIKE "2021%"
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;