SELECT A.FLAVOR
FROM (
            SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
            FROM FIRST_HALF
            GROUP BY FLAVOR
) A
INNER JOIN (
            SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
            FROM JULY
            GROUP BY FLAVOR
) B ON A.FLAVOR = B.FLAVOR
GROUP BY A.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.TOTAL_ORDER) DESC
LIMIT 3;