SELECT
    B.HISTORY_ID,
    TRUNCATE(
         CASE WHEN USE_DATE BETWEEN 7 AND 29 THEN (A.DAILY_FEE * 0.95) * B.USE_DATE
              WHEN USE_DATE BETWEEN 30 AND 89 THEN (A.DAILY_FEE * 0.92) * B.USE_DATE
              WHEN USE_DATE >= 90 THEN (A.DAILY_FEE * 0.85) * B.USE_DATE
              ELSE A.DAILY_FEE * B.USE_DATE
        END, -1) AS FEE
FROM CAR_RENTAL_COMPANY_CAR A 
RIGHT JOIN (
            SELECT HISTORY_ID, CAR_ID, DATEDIFF(END_DATE, START_DATE)+1 AS USE_DATE
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
) B ON A.CAR_ID = B.CAR_ID
WHERE A.CAR_TYPE = "트럭"
ORDER BY FEE DESC, B.HISTORY_ID DESC;