SELECT DISTINCT CART_PRODUCTS.CART_ID
FROM CART_PRODUCTS, (
    SELECT *
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
) H
WHERE CART_PRODUCTS.CART_ID = H.CART_ID
AND CART_PRODUCTS.NAME = 'Milk'
ORDER BY CART_ID;